### ISSUE TITLE
Issue with Automation Tools

### ISSUE THREAD

**Issue by Chriswog** [matortheeternal/TES5EditScripts#22]
Hello, firstly, thank you so much for the Automation Tools. They've saved me hours of work. I'm just hoping they can continue to save me work

I've used them successfully thus far, but now I'm trying to use the Quick Change/Element Assign option and things are going weird.

I put in the path and the value I want, and TESV edit reports back it has successfully added the element to the record.

But there's nothing there. No change at all. I don't get that. Either it works and I'm good or it fails and I get an error, right?

I've run tests, I know I have my inputs correct. Using the same inputs, I can use the Remove option and it will find the element I tell it to at the path I put in.

Specifically, I'm trying to add races to the Additional Races section of the Armor Addons. Is this just something it's not able to do? Or am I doing something wrong? Without an error message, I have no idea where to start fixing this.

**Comment by matortheeternal** [comment]
![](http://puu.sh/Aol7i.png)

works fine for me.

**Comment by Chriswog** [comment]
Wow, I was not expecting such a quick response! Thank you! That was what I needed. I was using "Additional Races/MODL - Race" for the path, which worked elsewhere. So grateful for the help and the tool. You rock
